In [12]:
import psycopg2
from psycopg2 import Error
import pandas as pd
import random
import datetime
from datetime import timedelta
import string
import numpy as np

def found(lst, i, find):
    a = []
    for k in range(len(lst)):
        elem = lst[k]
        if find == elem[i]:
            a.append(k)
    return a
def random_date1(start_date, end_date):
    random_date = start_date + datetime.timedelta(days=random.randint(0, (end_date - start_date).days))
    return random_date

# количество записей
male = 735 * ['М']
female = 938 * ['Ж']
gender = male + female
P = 300 #количество человек
#создаем список имен
namedf = pd.read_csv('name.csv', usecols = ['name'])
namedf.insert(loc = 1, column = 'gender', value = gender)

#создаем список фамилий
surnamedf = pd.read_csv('surname.csv', usecols = ['surname'])
surname = surnamedf['surname']
#создаем паспорта
passport = [(str(random.randint(1000, 9999)) + " " + str(random.randint(100000, 999999))) for i in range(P)]
#создаем список номеров телефонов
phone = ['89' + str(random.randint(0,999999999)) for i in range(P)]
#создаем список номеров паролей
password = [str(random.randint(10000000, 10000000000000)) for i in range(P)]
#создаем список номеров льгот
fees = [random.choice(['TRUE', 'FALSE']) for i in range(P)]
#создаем список дат рождения
start_date = datetime.date(1900, 1, 1)
end_date = datetime.date(2023, 1, 1)
def random_date(start_date, end_date):
    random_date = start_date + datetime.timedelta(days=random.randint(0, (end_date - start_date).days))
    date = f"'{random_date.strftime('%Y-%m-%d')}'"
    return date

born_date = [random_date(start_date, end_date) for i in range(P)]
    
#создаем список email

email = []
def random_string(length):
    letters = string.ascii_lowercase
    rand_string = ''.join(random.choice(letters) for i in range(length))
    return rand_string
em = ['yandex.ru', 'gmail.ru', 'mail.ru']
for i in range(P):
    email.append(random_string(8) + '@' + random.choice(em))
    
#создаем списко логинов
login = [random_string(8) for i in range(P)]
try:
    # Подключиться к существующей базе данных
    connection = psycopg2.connect(user="azonchic",
                                  # пароль, который указали при установке PostgreSQL
                                  password="rgdbaza",
                                  host="127.0.0.1",
                                  port="5432",
                                  database="rgd")

    # Создайте курсор для выполнения операций с базой данных
    cursor = connection.cursor()
    delete_query = """delete from Passenger"""
    cursor.execute(delete_query)
    for i in range(P):
        num = str(i + 1)
        # выбираем случайное имя и фамилию
        k = random.randint(0, len(namedf) - 1)
        name = namedf.iloc[k]
        n = random.randint(0, len(surname) - 1)
        gender = namedf.iat[i,1]
        insert_query = """INSERT INTO Passenger (id, name, surname, 
                passport, phone_number, 
                password1, fees, born_date, 
                email, gender, login) VALUES (%s, %s, %s, %s,
                  %s, %s,
                  %s, %s, %s,
                  %s, %s)"""
        cursor.execute(insert_query, (i + 1, name[0], surname[n] + '(a)', passport[i],
                        phone[i], password[i], fees[i], born_date[i], email[i],
                                     gender, login[i]))
        connection.commit()
    # Выполнение команды: это создает новую таблицу
except (Exception, Error) as error:
    print("Ошибка при работе с PostgreSQL", error)
finally:
    if connection:
        cursor.close()
        connection.close()
        print("Соединение с PostgreSQL закрыто")

N = 200 #количество поездов
# задаем название таблицы
# table_name = 'Train'
# # задаем столбцы таблицы
# column_names = ('id', 'train_number', 'train_type', 'loc_model')
# #создаем список номеров
number = [str(random.randint(100, 999)) + random_string(2) for i in range(N)]
#создаем типы поездов
train_type = ['скоростной', 'высокоскоростной', 'фирменный']
#создаем список моделей локомотивов
loc_model = 'пассажирский'
# генерация и запись DML-скрипта в файл
numvan = [random.randint(3,8) for i in range(N)] #количество вагонов в каждом поезде
vanid = np.arange(1, sum(numvan) + 1, 1) # id для вагонов
vantype = [] # тип вагона
try:
    # Подключиться к существующей базе данных
    connection = psycopg2.connect(user="azonchic",
                                  # пароль, который указали при установке PostgreSQL
                                  password="rgdbaza",
                                  host="127.0.0.1",
                                  port="5432",
                                  database="rgd")

    # Создайте курсор для выполнения операций с базой данных
    cursor = connection.cursor()
    for i in range(N):
        insert_query = """INSERT INTO Train (id, train_number, train_type, 
                loc_model) VALUES (%s, %s, %s, %s)"""
        cursor.execute(insert_query, (i + 1, number[i], random.choice(train_type), 
                                     loc_model))
        connection.commit()

    # Выполнение команды: это создает новую таблицу
except (Exception, Error) as error:
    print("Ошибка при работе с PostgreSQL", error)
finally:
    if connection:
        cursor.close()
        connection.close()
        print("Соединение с PostgreSQL закрыто")
        
try:
    connection = psycopg2.connect(user="azonchic",
                                  # пароль, который указали при установке PostgreSQL
                                  password="rgdbaza",
                                  host="127.0.0.1",
                                  port="5432",
                                  database="rgd")
    
    cursor = connection.cursor()
    van_type = ['сидячий', 'плацкарт', 'купе']
    intrain = 'TRUE'
    id1 = 0
    for i in range(N):
        k = 0
        while k != numvan[i]:
            van_type1 = random.choice(van_type)
            vantype.append(van_type1)
            insert_query = """INSERT INTO Van (id, van_type, issue_year, vannumber,
            intrain, train_id) VALUES (%s, %s, %s, %s, %s,
                  %s)"""
            cursor.execute(insert_query, (id1 + 1, van_type1,
                    random_date(datetime.date(1970, 1, 1),datetime.date(2023, 1, 1)),
                      k+1, intrain, i+1))
            id1 += 1
            k += 1
    select_query = """select * from van"""
    cursor.execute(select_query)
    van1 = cursor.fetchall()
    connection.commit()
            
except (Exception, Error) as error:
    print("Ошибка при работе с PostgreSQL", error)
finally:
    if connection:
        cursor.close()
        connection.close()
        print("Соединение с PostgreSQL закрыто")

try:
    # Подключиться к существующей базе данных
    connection = psycopg2.connect(user="azonchic",
                                  # пароль, который указали при установке PostgreSQL
                                  password="rgdbaza",
                                  host="127.0.0.1",
                                  port="5432",
                                  database="rgd")
    cursor = connection.cursor()
    
    underwearlst = ['TRUE', 'FALSE']
    numplace = [random.randint(10, 20) for i in range(len(vantype))] #количество мест в каждом вагоне
    id1 = 0
    place = []
    for i in range(len(vantype)):
        c = 0
        place_type = vantype[i]
        if place_type == 'сидячий':
            underwear = underwearlst[1]
        else:
            underwear = underwearlst[0]
        while c != numplace[i]:
            insert_query = """ INSERT INTO Place (id, place_type, 
            underwear, place_number, van_id) VALUES (%s, %s, %s, %s, %s)"""
            cursor.execute(insert_query, (id1 + 1, place_type, underwear, c+1, i+1))
            id1 += 1
            c += 1
    select_query = """select * from place"""
    cursor.execute(select_query)
    place1 = cursor.fetchall()
    connection.commit()
    
    # Выполнение команды: это создает новую таблицу
except (Exception, Error) as error:
    print("Ошибка при работе с PostgreSQL", error)
finally:
    if connection:
        cursor.close()
        connection.close()
        print("Соединение с PostgreSQL закрыто")

stations = pd.read_csv('StationNames.csv', usecols = ['stations'])
city1 = pd.read_csv('city.csv')
city2 = city1['Город']
city = [city2[random.randint(0, len(city2) - 1)] for i in range(len(stations))]
country = ['Россия', 'Белоруссия', 'Узбекистан', 'Таджикистан', 'Армения',
          'Грузия', 'Азербайджан', 'Украина', "Киргизия", 'Казахстан']
phone = ['89' + str(random.randint(0,999999999)) for i in range(len(stations))]
director = pd.read_csv('name.csv', usecols = ['name'])
timezone = ['МСК+0', 'МСК+1','МСК+1', 'МСК+3', 'МСК+4', 'МСК+5']

try:
    # Подключиться к существующей базе данных
    connection = psycopg2.connect(user="azonchic",
                                  # пароль, который указали при установке PostgreSQL
                                  password="rgdbaza",
                                  host="127.0.0.1",
                                  port="5432",
                                  database="rgd")

    # Создайте курсор для выполнения операций с базой данных
    cursor = connection.cursor()
    for i in range(len(stations)):
        insert_query = """INSERT INTO Stations (id, stname, 
                city, way, 
                country, phone, 
                director, timezone) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)"""
        stations1 = stations.iloc[i]
        director1 = director.iloc[i]
        cursor.execute(insert_query, (i + 1, stations1[0], city[i], random.randint(2,5),
                        random.choice(country), phone[i], director1[0], random.choice(timezone)))
        connection.commit()
    # Выполнение команды: это создает новую таблицу
except (Exception, Error) as error:
    print("Ошибка при работе с PostgreSQL", error)
finally:
    if connection:
        cursor.close()
        connection.close()
        print("Соединение с PostgreSQL закрыто")

F = 200 #количество рейсов
flnumber = [random.randint(100, 999) for i in range(F)]
total_stop = []
dep_date = [random_date1(datetime.datetime(2023,1,1), 
                        datetime.datetime(2024,1,1)) for i in range(F)]
train_id = 0
try:
    # Подключиться к существующей базе данных
    connection = psycopg2.connect(user="azonchic",
                                  # пароль, который указали при установке PostgreSQL
                                  password="rgdbaza",
                                  host="127.0.0.1",
                                  port="5432",
                                  database="rgd")

    # Создайте курсор для выполнения операций с базой данных
    cursor = connection.cursor()
    for i in range(F):
        driver = director.iloc[i]
        n = random.randint(3, 8) #количестов остановок рейса
        total_stop.append(n)
        insert_query = """INSERT INTO Flight (id, flnumber, 
                dep_date, driver, total_stop, 
                train_id) VALUES (%s, %s, %s, %s, %s, %s)"""
        cursor.execute(insert_query, (i + 1, flnumber[i], dep_date[i], driver[0],
                                      n, train_id + 1))
        train_id += 1
    cursor.execute("""select * from Flight""")
    flight1 = cursor.fetchall()
    connection.commit()
    # Выполнение команды: это создает новую таблицу
except (Exception, Error) as error:
    print("Ошибка при работе с PostgreSQL", error)
finally:
    if connection:
        cursor.close()
        connection.close()
        print("Соединение с PostgreSQL закрыто")

stop_id = 0
stoptime = [datetime.timedelta(minutes=2), datetime.timedelta(minutes=5), 
            datetime.timedelta(minutes=7)]
try:
    # Подключиться к существующей базе данных
    connection = psycopg2.connect(user="azonchic",
                                  # пароль, который указали при установке PostgreSQL
                                  password="rgdbaza",
                                  host="127.0.0.1",
                                  port="5432",
                                  database="rgd")

    # Создайте курсор для выполнения операций с базой данных
    cursor = connection.cursor()
    for i in range(F):
        dep = dep_date[i] + datetime.timedelta(hours=random.randint(0,24),
                                              minutes=random.randint(0,60))
        arrive = dep_date[i] + datetime.timedelta(hours=random.randint(0,24),
                                              minutes=random.randint(0,60))
        station_id = random.sample(range(1,len(stations) + 1), total_stop[i])
        for k in range(total_stop[i]):
            if k == 0:
                insert_query = """INSERT INTO Stop (id, stnumber, 
                    waytime, stoptime, flight_id, waynumber,
                    station_id, dep_date, arrive_date) VALUES (%s, %s, %s, 
                    %s, %s, %s, %s, %s, %s)"""
                cursor.execute(insert_query, (stop_id + 1, k+1, datetime.timedelta(0),
                                              datetime.timedelta(0),
                                              i+1,
                                              random.randint(1,5),
                                             station_id[k],dep,arrive))
                stop_id += 1
                connection.commit()
            elif k != total_stop[i] - 1:
                waytime = datetime.timedelta(days=random.randint(0,1),
                                            hours=random.randint(0,24),
                                             minutes=random.randint(0,60))
                stop = random.choice(stoptime)
                dep = dep + stop + waytime
                arrive = arrive + waytime
                insert_query = """INSERT INTO Stop (id, stnumber, 
                    waytime, stoptime, flight_id, waynumber,
                    station_id, dep_date, arrive_date) VALUES (%s, %s, %s, 
                    %s, %s, %s, %s, %s, %s)"""
                cursor.execute(insert_query, (stop_id + 1, k+1,waytime,stop,i+1,
                                              random.randint(1,5),
                                              station_id[k],dep,arrive))
                stop_id += 1
                connection.commit()
            else:
                waytime = datetime.timedelta(days=random.randint(0,1),
                                            hours=random.randint(0,24),
                                             minutes=random.randint(0,60))
                stop = datetime.timedelta(0)
                dep = dep + waytime
                arrive = arrive + waytime
                insert_query = """INSERT INTO Stop (id, stnumber, 
                    waytime, stoptime, flight_id, waynumber,
                    station_id, dep_date, arrive_date) VALUES (%s, %s, %s, 
                    %s, %s, %s, %s, %s, %s)"""
                cursor.execute(insert_query, (stop_id + 1, k+1, waytime,stop,i+1,
                                              random.randint(1,5),station_id[k],
                                              dep,arrive))
                stop_id += 1
                connection.commit()
    select_query = """select * from stop"""
    cursor.execute(select_query)
    stop1 = cursor.fetchall()
    connection.commit()
                


    # Выполнение команды: это создает новую таблицу
except (Exception, Error) as error:
    print("Ошибка при работе с PostgreSQL", error)
finally:
    if connection:
        cursor.close()
        connection.close()
        print("Соединение с PostgreSQL закрыто")

ticket_id = 0
# try:
#     # Подключиться к существующей базе данных
#     connection = psycopg2.connect(user="azonchic",
#                                   # пароль, который указали при установке PostgreSQL
#                                   password="rgdbaza",
#                                   host="127.0.0.1",
#                                   port="5432",
#                                   database="rgd")

#     # Создайте курсор для выполнения операций с базой данных
#     cursor = connection.cursor()
#     for id1 in place_id:
#         plc_num = place1[id1-1][3]
#         van_id = place1[id1-1][4]
#         vannumber = van1[van_id-1][3]
#         place_type = van1[van_id-1][1]
#         train_id = van1[van_id-1][5]
#         flight_id = found(flight1,5,train_id)[0]
#         stop_id = found(stop1,4,flight_id)
#         dep = stop1[stop_id[0]][6]
#         dep_date = stop1[stop_id[0]][7]
#         arrive = stop1[stop_id[-1]][6]
#         arrive_date = stop1[stop_id[-1]][8]
#         insert_query = """INSERT INTO Ticket (id, place, van,
#         price,place_type,arrive_date,passenger_id,flight_id,
#         departure_id,arrive_id,place_id,dep_date) VALUES (%s, %s, %s,
#                     %s, %s, %s, %s, %s, %s,%s,%s,%s)"""
#         cursor.execute(insert_query, (ticket_id+1,plc_num,vannumber,
#                                      random.randint(500,5000),
#                                      place_type,arrive_date,random.randint(1,P),
#                                      flight_id,dep,arrive,id1,dep_date))
#         ticket_id += 1
#         connection.commit()
#     # Выполнение команды: это создает новую таблицу
# except (Exception, Error) as error:
#     print("Ошибка при работе с PostgreSQL", error)
# finally:
#     if connection:
#         cursor.close()
#         connection.close()
#         print("Соединение с PostgreSQL закрыто")
        
        
# try:
#     # Подключиться к существующей базе данных
#     connection = psycopg2.connect(user="azonchic",
#                                   # пароль, который указали при установке PostgreSQL
#                                   password="rgdbaza",
#                                   host="127.0.0.1",
#                                   port="5432",
#                                   database="rgd")

#     # Создайте курсор для выполнения операций с базой данных
#     cursor = connection.cursor()
#     for id1 in place_id:
#         plc_num = place1[id1-1][3]
#         van_id = place1[id1-1][4]
#         vannumber = van1[van_id-1][3]
#         place_type = van1[van_id-1][1]
#         train_id = van1[van_id-1][5]
#         flight_id = found(flight1,5,train_id)[0]
#         stop_id = found(stop1,4,flight_id)
#         dep = stop1[stop_id[0]][6]
#         dep_date = stop1[stop_id[0]][7]
#         arrive = stop1[stop_id[-1]][6]
#         arrive_date = stop1[stop_id[-1]][8]
#         insert_query = """INSERT INTO Ticket (id, place, van,
#         price,place_type,arrive_date,passenger_id,flight_id,
#         departure_id,arrive_id,place_id,dep_date) VALUES (%s, %s, %s,
#                     %s, %s, %s, %s, %s, %s,%s,%s,%s)"""
#         cursor.execute(insert_query, (ticket_id+1,plc_num,vannumber,
#                                      random.randint(500,5000),
#                                      place_type,arrive_date,random.randint(1,P),
#                                      flight_id,dep,arrive,id1,dep_date))
#         ticket_id += 1
#         connection.commit()
#     # Выполнение команды: это создает новую таблицу
# except (Exception, Error) as error:
#     print("Ошибка при работе с PostgreSQL", error)
# finally:
#     if connection:
#         cursor.close()
#         connection.close()
#         print("Соединение с PostgreSQL закрыто")

Соединение с PostgreSQL закрыто
Соединение с PostgreSQL закрыто
Соединение с PostgreSQL закрыто
Соединение с PostgreSQL закрыто
Соединение с PostgreSQL закрыто
[(1, 858, datetime.date(2023, 12, 28), 'Аарон ', 3, 1), (2, 264, datetime.date(2023, 2, 8), 'Аба', 4, 2), (3, 697, datetime.date(2023, 6, 9), 'Аббас', 7, 3), (4, 105, datetime.date(2023, 5, 27), 'Абд аль-Узза', 3, 4), (5, 479, datetime.date(2023, 1, 21), 'Абдуллах', 5, 5), (6, 271, datetime.date(2023, 5, 22), 'Абид', 6, 6), (7, 178, datetime.date(2023, 3, 27), 'Аботур', 3, 7), (8, 180, datetime.date(2023, 1, 31), 'Аввакум', 3, 8), (9, 106, datetime.date(2023, 8, 19), 'Август', 8, 9), (10, 114, datetime.date(2023, 12, 18), 'Авдей', 4, 10), (11, 440, datetime.date(2023, 6, 12), 'Авель', 3, 11), (12, 661, datetime.date(2023, 3, 16), 'Аверкий', 7, 12), (13, 610, datetime.date(2023, 1, 14), 'Авигдор', 3, 13), (14, 241, datetime.date(2023, 1, 8), 'Авирмэд', 4, 14), (15, 591, datetime.date(2023, 9, 7), 'Авксентий', 5, 15), (16, 531, datetime.date(2023, 1, 19), 'Авл', 6, 16), (17, 816, datetime.date(2023, 5, 11), 'Авнер', 8, 17), (18, 347, datetime.date(2023, 12, 6), 'Аврелий', 3, 18), (19, 259, datetime.date(2023, 3, 29), 'Автандил', 3, 19), (20, 443, datetime.date(2023, 11, 14), 'Автоном', 4, 20), (21, 986, datetime.date(2023, 8, 10), 'Агапит', 7, 21), (22, 303, datetime.date(2024, 1, 1), 'Агафангел', 5, 22), (23, 173, datetime.date(2023, 6, 15), 'Агафодор', 5, 23), (24, 560, datetime.date(2023, 11, 3), 'Агафон', 3, 24), (25, 829, datetime.date(2023, 7, 3), 'Аги', 4, 25), (26, 189, datetime.date(2023, 3, 17), 'Агриппа', 4, 26), (27, 159, datetime.date(2023, 3, 13), 'Адам', 5, 27), (28, 104, datetime.date(2023, 2, 28), 'Адар', 5, 28), (29, 500, datetime.date(2023, 12, 6), 'Адиль', 5, 29), (30, 180, datetime.date(2023, 7, 20), 'Адольф', 4, 30), (31, 303, datetime.date(2023, 1, 5), 'Адонирам', 3, 31), (32, 959, datetime.date(2023, 2, 23), 'Адриан', 5, 32), (33, 283, datetime.date(2023, 10, 26), 'Азамат', 5, 33), (34, 110, datetime.date(2023, 9, 28), 'Азарий', 3, 34), (35, 881, datetime.date(2023, 2, 13), 'Азат', 5, 35), (36, 912, datetime.date(2023, 5, 29), 'Азиз', 8, 36), (37, 716, datetime.date(2023, 4, 7), 'Азим', 4, 37), (38, 804, datetime.date(2023, 9, 10), 'Айварс', 3, 38), (39, 802, datetime.date(2023, 2, 23), 'Айдар', 5, 39), (40, 334, datetime.date(2023, 5, 9), 'Айрат', 6, 40), (41, 451, datetime.date(2023, 6, 18), 'Акакий', 3, 41), (42, 850, datetime.date(2023, 3, 5), 'Аквилий', 6, 42), (43, 793, datetime.date(2023, 5, 6), 'Акиф', 5, 43), (44, 735, datetime.date(2023, 5, 21), 'Акоп', 5, 44), (45, 812, datetime.date(2023, 12, 24), 'Аксель', 7, 45), (46, 634, datetime.date(2023, 7, 12), 'Алан', 8, 46), (47, 254, datetime.date(2023, 4, 15), 'Аланус', 4, 47), (48, 387, datetime.date(2023, 4, 5), 'Алек', 4, 48), (49, 109, datetime.date(2023, 4, 16), 'Александр', 6, 49), (50, 376, datetime.date(2023, 7, 25), 'Алексей', 7, 50), (51, 379, datetime.date(2023, 10, 6), 'Алемдар', 6, 51), (52, 341, datetime.date(2023, 2, 5), 'Алик', 3, 52), (53, 696, datetime.date(2023, 2, 7), 'Алим', 4, 53), (54, 529, datetime.date(2023, 12, 27), 'Алипий', 8, 54), (55, 117, datetime.date(2023, 3, 22), 'Алишер', 7, 55), (56, 834, datetime.date(2023, 7, 29), 'Алмат', 7, 56), (57, 322, datetime.date(2023, 1, 29), 'Алоиз', 8, 57), (58, 391, datetime.date(2023, 2, 1), 'Алон', 5, 58), (59, 500, datetime.date(2023, 10, 10), 'Альберик', 5, 59), (60, 833, datetime.date(2023, 5, 1), 'Альберт', 6, 60), (61, 383, datetime.date(2023, 1, 5), 'Альбин', 8, 61), (62, 130, datetime.date(2023, 3, 27), 'Альваро', 8, 62), (63, 244, datetime.date(2023, 9, 18), 'Альвиан', 5, 63), (64, 836, datetime.date(2023, 3, 2), 'Альвизе', 3, 64), (65, 205, datetime.date(2023, 3, 14), 'Альфонс', 5, 65), (66, 640, datetime.date(2023, 7, 22), 'Альфред', 6, 66), (67, 624, datetime.date(2023, 11, 8), 'Амадис', 5, 67), (68, 946, datetime.date(2023, 5, 29), 'Амвросий', 7, 68), (69, 937, datetime.date(2023, 11, 29), 'Амедей', 4, 69), (70, 833, datetime.date(2023, 1, 25), 'Амин', 6, 70), (71, 515, datetime.date(2023, 10, 6), 'Амир', 7, 71), (72, 642, datetime.date(2023, 11, 13), 'Амр', 3, 72), (73, 119, datetime.date(2023, 4, 24), 'Амфилохий', 4, 73), (74, 946, datetime.date(2023, 12, 5), 'Анания', 5, 74), (75, 272, datetime.date(2023, 10, 29), 'Анас', 8, 75), (76, 567, datetime.date(2023, 1, 28), 'Анастасий', 6, 76), (77, 136, datetime.date(2023, 8, 25), 'Анатолий', 6, 77), (78, 382, datetime.date(2023, 5, 6), 'Ангеляр', 6, 78), (79, 427, datetime.date(2023, 2, 2), 'Андокид', 3, 79), (80, 274, datetime.date(2023, 2, 16), 'Андрей', 3, 80), (81, 735, datetime.date(2023, 12, 12), 'Андроник', 4, 81), (82, 271, datetime.date(2023, 7, 14), 'Аннерс', 6, 82), (83, 364, datetime.date(2023, 7, 9), 'Анри', 6, 83), (84, 184, datetime.date(2023, 6, 10), 'Ансельм', 6, 84), (85, 811, datetime.date(2023, 5, 11), 'Антипа', 7, 85), (86, 720, datetime.date(2023, 7, 25), 'Антон', 3, 86), (87, 849, datetime.date(2023, 5, 8), 'Антоний', 4, 87), (88, 676, datetime.date(2023, 1, 25), 'Антонин', 8, 88), (89, 896, datetime.date(2023, 9, 11), 'Антуан', 6, 89), (90, 870, datetime.date(2023, 3, 8), 'Арам', 7, 90), (91, 891, datetime.date(2023, 12, 28), 'Арефа', 5, 91), (92, 494, datetime.date(2023, 1, 26), 'Арзуман', 4, 92), (93, 722, datetime.date(2023, 5, 16), 'Аристарх', 5, 93), (94, 776, datetime.date(2023, 6, 17), 'Аристон', 5, 94), (95, 292, datetime.date(2023, 5, 26), 'Ариф', 4, 95), (96, 530, datetime.date(2023, 4, 7), 'Аркадий', 6, 96), (97, 367, datetime.date(2023, 4, 9), 'Арсений', 4, 97), (98, 448, datetime.date(2023, 11, 9), 'Артём', 7, 98), (99, 821, datetime.date(2023, 8, 15), 'Артур', 8, 99), (100, 532, datetime.date(2023, 5, 9), 'Арфаксад', 6, 100), (101, 574, datetime.date(2023, 4, 29), 'Асаф', 7, 101), (102, 201, datetime.date(2023, 6, 23), 'Атанасий', 3, 102), (103, 535, datetime.date(2023, 2, 25), 'Атом', 6, 103), (104, 669, datetime.date(2023, 5, 8), 'Аттик', 6, 104), (105, 168, datetime.date(2023, 10, 6), 'Афанасий', 6, 105), (106, 601, datetime.date(2023, 3, 4), 'Афинагор', 3, 106), (107, 354, datetime.date(2023, 7, 8), 'Афиней', 3, 107), (108, 526, datetime.date(2023, 11, 7), 'Афиф', 8, 108), (109, 896, datetime.date(2023, 5, 26), 'Африкан', 7, 109), (110, 793, datetime.date(2023, 12, 6), 'Ахилл', 8, 110), (111, 618, datetime.date(2023, 9, 16), 'Ахмад', 5, 111), (112, 305, datetime.date(2023, 4, 20), 'Ахтям', 4, 112), (113, 385, datetime.date(2023, 12, 20), 'Ашот', 3, 113), (114, 332, datetime.date(2023, 6, 9), 'Бадар', 5, 114), (115, 671, datetime.date(2023, 9, 21), 'Барни', 4, 115), (116, 777, datetime.date(2023, 4, 10), 'Бартоломео', 8, 116), (117, 741, datetime.date(2023, 8, 18), 'Басир', 3, 117), (118, 855, datetime.date(2023, 10, 10), 'Бахтияр', 7, 118), (119, 908, datetime.date(2023, 6, 9), 'Баян', 7, 119), (120, 450, datetime.date(2023, 8, 5), 'Безсон', 6, 120), (121, 968, datetime.date(2023, 9, 29), 'Бен', 3, 121), (122, 982, datetime.date(2023, 9, 3), 'Беньямин', 3, 122), (123, 210, datetime.date(2023, 9, 13), 'Берт', 4, 123), (124, 854, datetime.date(2023, 4, 14), 'Бехруз', 8, 124), (125, 925, datetime.date(2023, 7, 25), 'Билял', 3, 125), (126, 705, datetime.date(2023, 2, 7), 'Богдан', 8, 126), (127, 922, datetime.date(2023, 10, 16), 'Болеслав', 6, 127), (128, 566, datetime.date(2023, 10, 24), 'Бонавентура', 5, 128), (129, 621, datetime.date(2023, 12, 16), 'Борис', 8, 129), (130, 545, datetime.date(2023, 3, 18), 'Борислав', 3, 130), (131, 775, datetime.date(2023, 8, 13), 'Боян', 3, 131), (132, 365, datetime.date(2023, 1, 22), 'Бронислав', 8, 132), (133, 278, datetime.date(2023, 8, 28), 'Брячислав', 6, 133), (134, 506, datetime.date(2023, 10, 27), 'Бурхан', 4, 134), (135, 440, datetime.date(2023, 6, 23), 'Бутрос', 8, 135), (136, 326, datetime.date(2023, 12, 21), 'Бямбасурэн', 7, 136), (137, 238, datetime.date(2023, 2, 17), 'Вадим', 8, 137), (138, 910, datetime.date(2023, 5, 7), 'Валентин', 5, 138), (139, 446, datetime.date(2023, 2, 2), 'Валентино', 3, 139), (140, 438, datetime.date(2023, 7, 14), 'Валерий', 4, 140), (141, 733, datetime.date(2023, 9, 9), 'Валерьян', 3, 141), (142, 432, datetime.date(2023, 10, 7), 'Вальдемар', 5, 142), (143, 563, datetime.date(2023, 12, 8), 'Вангьял', 6, 143), (144, 120, datetime.date(2023, 7, 25), 'Варлам', 4, 144), (145, 668, datetime.date(2023, 6, 10), 'Варнава', 3, 145), (146, 954, datetime.date(2023, 4, 7), 'Варфоломей', 7, 146), (147, 961, datetime.date(2023, 8, 28), 'Василий', 5, 147), (148, 676, datetime.date(2023, 11, 24), 'Вахтанг', 4, 148), (149, 362, datetime.date(2023, 12, 28), 'Велвел', 8, 149), (150, 517, datetime.date(2023, 4, 21), 'Венансио', 4, 150), (151, 947, datetime.date(2023, 6, 11), 'Венедикт', 5, 151), (152, 524, datetime.date(2023, 10, 5), 'Вениамин', 3, 152), (153, 765, datetime.date(2023, 4, 6), 'Венцеслав', 8, 153), (154, 412, datetime.date(2023, 9, 22), 'Вигго', 7, 154), (155, 195, datetime.date(2023, 2, 1), 'Викентий', 8, 155), (156, 179, datetime.date(2023, 9, 24), 'Виктор', 4, 156), (157, 319, datetime.date(2023, 11, 8), 'Викторин', 3, 157), (158, 818, datetime.date(2023, 6, 18), 'Вильгельм', 6, 158), (159, 751, datetime.date(2023, 2, 20), 'Винцас', 4, 159), (160, 456, datetime.date(2023, 10, 1), 'Виссарион', 5, 160), (161, 229, datetime.date(2023, 9, 18), 'Виталий', 8, 161), (162, 551, datetime.date(2023, 10, 8), 'Витаутас', 8, 162), (163, 314, datetime.date(2023, 5, 21), 'Вито', 6, 163), (164, 899, datetime.date(2023, 8, 17), 'Владимир', 6, 164), (165, 116, datetime.date(2023, 1, 10), 'Владислав', 5, 165), (166, 895, datetime.date(2023, 7, 5), 'Владлен', 5, 166), (167, 174, datetime.date(2023, 10, 16), 'Влас', 7, 167), (168, 775, datetime.date(2023, 1, 27), 'Воислав', 7, 168), (169, 419, datetime.date(2023, 7, 8), 'Володарь', 3, 169), (170, 117, datetime.date(2023, 7, 3), 'Вольфганг', 6, 170), (171, 613, datetime.date(2023, 3, 27), 'Вописк', 7, 171), (172, 150, datetime.date(2023, 9, 7), 'Всеволод', 7, 172), (173, 469, datetime.date(2023, 8, 14), 'Всеслав', 7, 173), (174, 270, datetime.date(2023, 4, 23), 'Вук', 3, 174), (175, 389, datetime.date(2023, 5, 5), 'Вукол', 6, 175), (176, 455, datetime.date(2023, 12, 7), 'Вышеслав', 6, 176), (177, 296, datetime.date(2023, 6, 18), 'Вячеслав', 5, 177), (178, 256, datetime.date(2023, 1, 1), 'Габриеле', 7, 178), (179, 900, datetime.date(2023, 8, 24), 'Гавриил', 4, 179), (180, 379, datetime.date(2023, 6, 8), 'Гай', 6, 180), (181, 260, datetime.date(2023, 1, 12), 'Галактион', 5, 181), (182, 404, datetime.date(2023, 10, 29), 'Галымжан', 8, 182), (183, 342, datetime.date(2023, 1, 26), 'Гамлет', 3, 183), (184, 161, datetime.date(2023, 7, 5), 'Гаспар', 5, 184), (185, 638, datetime.date(2023, 1, 1), 'Гафур', 4, 185), (186, 805, datetime.date(2023, 2, 27), 'Гвидо', 6, 186), (187, 686, datetime.date(2023, 7, 12), 'Гейдар', 8, 187), (188, 322, datetime.date(2023, 4, 18), 'Геласий', 7, 188), (189, 484, datetime.date(2023, 5, 27), 'Гелий', 7, 189), (190, 208, datetime.date(2023, 9, 27), 'Гельмут', 8, 190), (191, 843, datetime.date(2023, 4, 15), 'Геннадий', 7, 191), (192, 472, datetime.date(2023, 7, 22), 'Генри', 5, 192), (193, 910, datetime.date(2023, 10, 5), 'Генрих', 4, 193), (194, 708, datetime.date(2023, 10, 19), 'Георге', 5, 194), (195, 947, datetime.date(2023, 12, 3), 'Георгий', 4, 195), (196, 225, datetime.date(2023, 9, 28), 'Гераклид', 4, 196), (197, 482, datetime.date(2023, 4, 25), 'Герасим', 7, 197), (198, 831, datetime.date(2023, 8, 24), 'Герберт', 5, 198), (199, 636, datetime.date(2023, 4, 9), 'Герман', 7, 199), (200, 545, datetime.date(2023, 10, 23), 'Германн', 6, 200)]
Соединение с PostgreSQL закрыто

Соединение с PostgreSQL закрыто

In [33]:
print(random.sample(range(1,len(stations) + 1), total_stop[0]))

[66, 73, 10, 14, 63, 81, 98]

In [49]:
def random_date(start_date, end_date):
    random_date = start_date + datetime.timedelta(days=random.randint(0, (end_date - start_date).days))
    return random_date
print([random_date(datetime.datetime(2023,1,1),datetime.datetime(2023,4,1))])

[datetime.datetime(2023, 3, 1, 0, 0)]

In [56]:
print(datetime.timedelta(days=random.randint(0,1),
                                            hours=random.randint(0,24),
                                             minutes=random.randint(0,60)))

1 day, 1:18:00